# Generated by Django 5.2.8 on 2025-11-29 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous_users', '0001_initial'),
        ('blog_post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLikeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to='blog_post.post')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_posts', to='anonymous_users.anonymoususer')),
            ],
            options={
                'verbose_name': '点赞记录',
                'verbose_name_plural': '点赞记录',
                'indexes': [models.Index(fields=['visitor', 'post'], name='blog_post_p_visitor_a5b81d_idx')],
                'unique_together': {('visitor', 'post')},
            },
        ),
        migrations.CreateModel(
            name='PostViewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='浏览时间')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_views', to='blog_post.post')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_posts', to='anonymous_users.anonymoususer')),
            ],
            options={
                'verbose_name': '浏览记录',
                'verbose_name_plural': '浏览记录',
                'indexes': [models.Index(fields=['visitor', 'post'], name='blog_post_p_visitor_b1b88f_idx')],
                'unique_together': {('visitor', 'post')},
            },
        ),
    ]
