# Generated by Django 5.2.8 on 2025-11-29 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0002_postlikerecord_postviewrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
