# Generated by Django 5.2.8 on 2025-11-26 08:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser_fingerprint', models.CharField(max_length=128, unique=True, verbose_name='浏览器指纹哈希')),
                ('nickname', models.CharField(max_length=50, unique=True, verbose_name='匿名昵称')),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now, verbose_name='首次访问时间')),
            ],
            options={
                'verbose_name': '匿名用户',
                'verbose_name_plural': '匿名用户',
            },
        ),
    ]
