# Generated by Django 5.2.8 on 2025-11-27 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloguser',
            old_name='github_username',
            new_name='github_home_link',
        ),
    ]
