# Generated by Django 5.2.8 on 2025-11-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_user', '0002_rename_github_username_bloguser_github_home_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', '男'), ('female', '女'), ('prefer_not_to_say', '不愿透露')], max_length=20, verbose_name='性别'),
        ),
    ]
