# Generated by Django 5.2.8 on 2025-11-28 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_user', '0003_alter_bloguser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloguser',
            name='nickname',
        ),
    ]
