# Generated by Django 5.2.8 on 2025-11-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_user', '0004_remove_bloguser_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='生日'),
        ),
    ]
